### ISSUE TITLE
Suggesting minor changes to README and maybe groq_runner.py

### ISSUE THREAD

**Issue by yukiCodesStuff** [jkelly8823/grad_research#1]
Hey Jacob, as title states I'd like to propose some minor suggestions:

README: Probably doesn't matter all that much since there weren't many packages needed but would save a little bit of time to have these included in the README

`
0. **Dependencies**
  ```
    pip install python-dotenv
    pip install groq
  ```
`

Also the `.env` file seems to be out of date, the `groq_runner.py` script uses 3 groq clients rather than 2, so might need an edit there.

groq_runner.py: Totally unnecessary but had I not been watching the directories I wouldn't have noticed any work being done by the program, I think this minor modification could show the user the script is running maybe?

```
    fileCt = 0
    for i in msg_content:
        print("Files Groq'd %6d" % fileCt, end='\r')
        fileCt += 1
```

I'm sure there's a more elegant way of doing this

**Comment by jkelly8823** [comment]
Thanks for the suggestions! Should be added now
